### ISSUE TITLE
DefaultColsMixin created_utc and updated_utc fields should default to UTC

### ISSUE THREAD

**Issue by bchopson** [level12/keg-elements#114]
The current default is `arrow.now`, should be `arrow.utcnow`. Should not require a migration since the server default and column types are correct.

**Comment by rsyring** [comment]
Per some testing we did, it turns out that `arrow.now()` unlike `datetime.now()` contains an offset.  Therefore, PostgreSQL was correctly saving the UTC time in the database.

The change in #128 is therefore just cosmetic to make it more clear in the code that the UTC time is actually being used/saved.
