### ISSUE TITLE
ModelForm Requires Precision and Scale to be Set on Numeric Columns

### ISSUE THREAD

**Issue by calebsyring** [level12/keg-elements#133]
It seems to create validators for a `ModelForm` any Numeric columns on the model are assumed to have both precision and scale set: (focus on lines 367-368)
https://github.com/level12/keg-elements/blob/0ea69ab464c61c93338196d167c220859130196b/keg_elements/forms/__init__.py#L365-L371
https://github.com/level12/keg-elements/blob/0ea69ab464c61c93338196d167c220859130196b/keg_elements/forms/__init__.py#L312-L313

I was setting up a `ModelForm` for a model with a Numeric column on which precision and scale were _not_ set. It failed like this:
```
keg_elements/forms/__init__.py:315: in _max_for_numeric
    return Decimal('{}.{}'.format('9' * (digits - scale), '9' * scale))
E   TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

In my mind there are two possible directions to go with a fix for this:

1. We still want to require Numeric columns to have precision and scale set in order for us to generate validators for that form field. In which case, we should probably assert that precision and scale are set, and if they aren't give a more helpful error message.
2. We do not want to require Numeric columns to have precision and scale set. In which case, we should probably not call `_max_for_numeric` if either value is missing.

**Comment by guruofgentoo** [comment]
Just about all of our numeric db columns have precision and scale specified, which is why this probably didn't come up before. Having those set explicitly in the model helps those who read the code know what kind of data they're dealing with.

I'd go one further than solution number 1 - I'd add asserts to our model column tests to ensure these values are set. Also have asserts in the form for more helpful error messages if needed, but these conditions should be asserted at the source, instead of waiting for the model to be used in a form.
